---
title: "Seminário 2 - Aplicação de um modelo Geoestatístico"
output:
  html_document:
    df_print: paged
---

# Uso de métodos estatísticos a fim de explorar ouro no território brasileiro

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Bibliotecas
```{r, warning=FALSE,echo=FALSE}
library(sf)
library(ggplot2)
library(dplyr)
library(foreign)
library(leaflet)
library(leaflet.extras)
library(lattice)
library(gstat)
library(sp)
library(geostats)
data("earthquakes")
```

## Limpeza do banco de dados

```{r}
dados = earthquakes %>%
  filter(year==2020) %>%
  st_as_sf(coords = c("lon", "lat")) %>%
  st_set_crs(4326)

asia_bbox <- st_as_sfc(st_bbox(c(xmin = 25, ymin = 5, xmax = 150, ymax = 50), crs = 4326))
japan_bbox <- japan_bbox <- st_as_sfc(st_bbox(c(xmin = 122, ymin = 24, xmax = 153, ymax = 46), crs = 4326))

# Filter points within Asia
#asia_only <- dados %>%
#  filter(st_intersects(geometry, asia_bbox, sparse = FALSE))
japan_only <- dados %>%
  filter(st_intersects(geometry, japan_bbox, sparse = FALSE))

color_scale <- colorNumeric(palette = "YlOrRd", domain = japan_only$mag)

# Create a leaflet map
leaflet(data = japan_only) %>%
  addTiles() %>%  # Add base map tiles
  addCircleMarkers(
    radius = ~mag,
    color = ~color_scale(mag),
    stroke = FALSE,
    fillOpacity = 0.8,
    popup = ~paste("Magnitude:", mag)
  )
```

## Variograma

```{r}
hist(japan_only$mag)
hist(log(japan_only$mag))

# variograma <- variogram(mag ~ 1, data = japan_only)
# variograma  
# 
# plot(variograma)
```

A variável é assimétrica, e a transformação log não resolve. Então a abordagem clássica não é recomendada. Assim, o ideal é realizar um modelo INLA.


## INLA

```{r}
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
library(INLA)

# 1) mesh to cover the area
mesh <- inla.mesh.2d(loc = japan_only$geometry, max.edge = c(1, 5))
plot(mesh)
points(st_coordinates(japan_only), col = "red")

# 2) SPDE model
spde <- inla.spde2.matern(mesh = mesh)

# 3) index set
s.index <- inla.spde.make.index("spatial", spde$n.spde)
#spatial <- inla.spde.make.index(name = "spatial", n.spde = spde$n.spde)

# 4) projection matrix
locs <- as.matrix(st_coordinates(japan_only$geometry))
A <- inla.spde.make.A(mesh = mesh, loc = locs)

# 5) prediction locations
coords <- st_coordinates(japan_only)
x_range <- range(coords[, 1])  
y_range <- range(coords[, 2])  
spacing <- 0.75  
pred.grid <- expand.grid(
  x = seq(from = x_range[1], to = x_range[2], by = spacing),
  y = seq(from = y_range[1], to = y_range[2], by = spacing)
)
plot(japan_only$geometry, main = "Grade de Previsão")
points(pred.grid$x, pred.grid$y, col = "red", pch = 20, cex = 0.5)

# 6) prediction projection matrix
A.pred = inla.spde.make.A(mesh = mesh, loc = as.matrix(pred.grid))

# 7) stacks
# Criando o stack de estimação
est.stack <- inla.stack(
  data = list(y = japan_only$mag),          # Variável resposta
  A = A,                         # Matriz A e intercepto
  effects = list(
    s.index = 1:spde$n.spde,              # Índices do efeito espacial
    data.frame(b0 = 1)                    # Intercepto (sem covariáveis)
  ),
  tag = "est"
)
# Criando o stack de previsão
pred.stack <- inla.stack(
  data = list(y = NA),                   # Resposta desconhecida para previsão
  A = A.pred,
  effects = list(
    s.index = 1:spde$n.spde,             # Efeito espacial
    data.frame(b0 = 1)                   # Intercepto
  ),
  tag = "pred"
)
full.stack = inla.stack(est.stack, pred.stack)

# 8) model formula
f <- y ~ 1 + f(s.index, model = spde)

# 9) run the model
results = inla(f, family = "gamma",
  #control.family = list(link = "logit"),
  data = inla.stack.data(full.stack),
  control.predictor = list(
    compute = TRUE,
    A = inla.stack.A(full.stack)
  )
)

#  *** inla.core.safe:  The inla program failed, but will rerun in case better initial values may help. try=1/1 
# Error in inla.core.safe(formula = formula, family = family, contrasts = contrasts,  : 
#   78 rows in 'control.predictor=list(A=A)'-matrix, contain only zeros. This is not allowed.
# The inla program failed and the maximum number of tries has been reached.

```